return {
  name = "luvit",
  version = "2.0.0",
  dependencies = {
    "creationix/pretty-print@0.1.0",
    "creationix/readline@1.0.1",
    "creationix/require@1.0.1",
    "creationix/http-codec@0.1.3",
    "creationix/json@2.5.0",
    "creationix/luvit-globals@0.0.1",
    utils = "creationix/luvit-utils@0.0.1",
    process = "creationix/luvit-process@0.0.1",
    timer = "creationix/luvit-timer@0.0.1",
    core = "creationix/luvit-core@0.0.1",
    fs = "creationix/luvit-fs@0.0.1",
    stream = "creationix/luvit-stream@0.0.1",
    repl = "creationix/luvit-repl@0.0.2",
    dgram = "creationix/luvit/dgram@0.0.1",
    dns = "creationix/luvit/dns@0.0.1",
    net = "creationix/luvit/net@0.0.1",
    path = "creationix/luvit/path@0.0.2",
    http = "creationix/luvit/http@0.0.1",
    https = "creationix/luvit/https@0.0.1",
    tls = "creationix/luvit/tls@0.0.1",
    codec = "creationix/luvit/codec@0.0.1",
    buffer = "creationix/luvit/buffer@0.0.1",
    childprocess = "creationix/luvit/childprocess@0.0.1",
  },
}
